/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/Layout/common/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/Layout/common/AppHeader.vue')['default']
    ApplicationSetting: typeof import('./src/components/Setting/ApplicationSetting.vue')['default']
    AppLogo: typeof import('./src/components/Logo/AppLogo.vue')['default']
    AppSider: typeof import('./src/components/Layout/common/AppSider.vue')['default']
    BasicLayout: typeof import('./src/components/Layout/BasicLayout.vue')['default']
    LayoutButton: typeof import('./src/components/Setting/LayoutButton.vue')['default']
    LoginComponent: typeof import('./src/components/Login/LoginComponent.vue')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NBreadcrumb: typeof import('naive-ui')['NBreadcrumb']
    NBreadcrumbItem: typeof import('naive-ui')['NBreadcrumbItem']
    NButton: typeof import('naive-ui')['NButton']
    NButtonGroup: typeof import('naive-ui')['NButtonGroup']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NColorPicker: typeof import('naive-ui')['NColorPicker']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDivider: typeof import('naive-ui')['NDivider']
    NDrawer: typeof import('naive-ui')['NDrawer']
    NDrawerContent: typeof import('naive-ui')['NDrawerContent']
    NFlex: typeof import('naive-ui')['NFlex']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NGi: typeof import('naive-ui')['NGi']
    NGradientText: typeof import('naive-ui')['NGradientText']
    NGrid: typeof import('naive-ui')['NGrid']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutFooter: typeof import('naive-ui')['NLayoutFooter']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NMenu: typeof import('naive-ui')['NMenu']
    NoSiderLayout: typeof import('./src/components/Layout/NoSiderLayout.vue')['default']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpace: typeof import('naive-ui')['NSpace']
    NSwitch: typeof import('naive-ui')['NSwitch']
    RegisterComponent: typeof import('./src/components/Login/RegisterComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RouteView: typeof import('./src/components/Layout/RouteView.vue')['default']
    SiderLayout: typeof import('./src/components/Layout/SiderLayout.vue')['default']
    Vditor: typeof import('./src/components/Markdown/Vditor.vue')['default']
  }
}
